### ISSUE TITLE
The code seems to be too complex

### ISSUE THREAD

**Issue by ghost** [TheBoringDude/siffer#1]
Rot13 is a straightforward algorithm - it basically shifts letters by 13 positions. Why not just use basic math over chars? An example from Rosetta Code https://rosettacode.org/wiki/Rot-13#Nim adapted to strings (and a bit optimized with preallocation):

```nim
import std/strutils

# func means proc with a {.noSideEffect.} pragma
func rot13(str: string): string =
  result = newString(str.len)
  # iterate over each char in the string, giving its index and the char itself
  for i, c in str:
    result[i] = 
      case toLowerAscii(c)
      of 'a'..'m': chr(ord(c) + 13)
      of 'n'..'z': chr(ord(c) - 13)
      else: c

echo rot13("hello world")
echo rot13("HELLO WOrld")

# rot13(rot13(x)) will return the original string x
# because that's how rot13 works
echo rot13(rot13("hello world"))
echo rot13(rot13("HELLO WOrld"))
```

**Comment by SolitudeSF** [comment]
pr's are welcome

**Comment by tbdsux** [comment]
didn't know anyone will take interest over this simple project, I am a very beginner with Nim :sweat_smile: and this project was just meant for practice :sweat_smile:

btw, for the code, .. it was on purpose to be re-usable for other rotation ciphers, not only `rot13` :blush:

**Comment by tbdsux** [comment]
I have accepted this change. Thank you very much for mentioning a better approach @Yardanico ...

I learned something from the code itself. :blush:
